# Generated by Django 5.2.7 on 2025-10-07 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_rawmessage_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmessage',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
