# Generated by Django 5.2.7 on 2025-10-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_rawmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('gateway_type', models.CharField(max_length=50)),
                ('destination_number', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_payment', to='payments.rawmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSING', 'Processing'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_PROCESSED', max_length=20)),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parsed_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='payments.parsedpayment')),
            ],
        ),
    ]
