version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WS_URL=${VITE_WS_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paymentsystem-frontend.rule=Host(`app.eagleshop.cloud`,`kitengela.eagleshop.cloud`)"
      - "traefik.http.routers.paymentsystem-frontend.entrypoints=websecure"
      - "traefik.http.routers.paymentsystem-frontend.tls=true"
      - "traefik.http.routers.paymentsystem-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.paymentsystem-frontend.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
