# Generated by Django 5.2.7 on 2025-12-16 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='performed_by_user',
            field=models.ForeignKey(blank=True, help_text='User who performed this movement (ForeignKey)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_registration',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this a registration transaction (special handling)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the transaction was processed', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed this transaction (changed to PROCESSING)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='performed_by',
            field=models.CharField(blank=True, help_text='User who performed this movement (legacy string field)', max_length=255),
        ),
    ]
