# Generated by Django 5.2.7 on 2025-10-07 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmessage',
            name='raw_text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1024)]),
        ),
        migrations.AlterField(
            model_name='rawmessage',
            name='received_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
