# Generated by Django 5.2.7 on 2025-12-16 08:24

from django.db import migrations
from decimal import Decimal


def create_registration_kit(apps, schema_editor):
    """Create Registration Kit product and category if they don't exist."""
    Product = apps.get_model('payments', 'Product')
    ProductCategory = apps.get_model('payments', 'ProductCategory')

    # Get or create Registration category
    category, created = ProductCategory.objects.get_or_create(
        name='Registration',
        defaults={
            'description': 'Registration kit products for new members'
        }
    )

    # Create Registration Kit product
    Product.objects.get_or_create(
        prod_code='REG_KIT_001',
        defaults={
            'prod_name': 'Registration Kit',
            'sku': 'REGKIT001',
            'sku_name': 'Standard Registration Kit',
            'current_price': Decimal('0.00'),
            'cost_price': Decimal('0.00'),
            'current_pv': Decimal('0.00'),
            'quantity': 100,
            'reorder_level': 10,
            'category': category,
            'is_active': True
        }
    )


def reverse_registration_kit(apps, schema_editor):
    """Remove Registration Kit product and category."""
    Product = apps.get_model('payments', 'Product')
    ProductCategory = apps.get_model('payments', 'ProductCategory')

    # Delete Registration Kit
    Product.objects.filter(prod_code='REG_KIT_001').delete()

    # Optionally delete Registration category if no other products use it
    category = ProductCategory.objects.filter(name='Registration').first()
    if category and not category.products.exists():
        category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_inventorymovement_performed_by_user_and_more'),
    ]

    operations = [
        migrations.RunPython(create_registration_kit, reverse_registration_kit),
    ]
