# Generated by Django 5.2.7 on 2025-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_seed_registration_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PROCESSOR', 'Processor'), ('ISSUER', 'Issuer')], db_index=True, default='ADMIN', help_text='User role determines access permissions', max_length=20),
        ),
    ]
