# Generated by Django 5.2.7 on 2025-10-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_parsedpayment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedpayment',
            name='raw_message',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('gateway_type', models.CharField(max_length=50)),
                ('destination_number', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSING', 'Processing'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_PROCESSED', max_length=20)),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('unique_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
                ('raw_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.rawmessage')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ParsedPayment',
        ),
    ]
