# Generated by Django 5.2.7 on 2025-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Product barcode for scanning (can be same as SKU or different)', max_length=200, null=True),
        ),
    ]
