# Generated by Django 5.2.7 on 2025-10-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_parsedpayment_raw_message_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='raw_message',
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_messages', to='payments.transaction'),
        ),
    ]
