# Generated by Django 5.2.7 on 2025-10-09 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_transaction_raw_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('PDQ', 'PDQ/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], help_text='How the payment was received', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (e.g., bank transaction ID, PDQ receipt number)', max_length=100)),
                ('payer_name', models.CharField(help_text='Name of person who made the payment', max_length=255)),
                ('payer_phone', models.CharField(blank=True, help_text='Phone number of payer (optional)', max_length=50)),
                ('payer_email', models.EmailField(blank=True, help_text='Email address of payer (optional)', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received', max_digits=10)),
                ('payment_date', models.DateTimeField(help_text='When the payment was received')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('created_by', models.CharField(help_text='Staff member who entered this payment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(help_text='Transaction created from this manual entry', on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='payments.transaction')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['-payment_date'], name='payments_ma_payment_028bb7_idx'), models.Index(fields=['payment_method'], name='payments_ma_payment_33047f_idx'), models.Index(fields=['reference_number'], name='payments_ma_referen_5f4f42_idx')],
            },
        ),
    ]
