# Generated by Django 5.2.7 on 2025-12-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_import_products_from_excel'),
    ]

    operations = [
        # Rename the ProductCategory model to ProductLine
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductLine',
        ),

        # Rename the parent_category field to parent_line
        migrations.RenameField(
            model_name='productline',
            old_name='parent_category',
            new_name='parent_line',
        ),

        # Rename the category field on Product to product_line
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_line',
        ),

        # Update the verbose names (Django will handle this through model Meta)
        migrations.AlterModelOptions(
            name='productline',
            options={'ordering': ['name'], 'verbose_name': 'Product Line', 'verbose_name_plural': 'Product Lines'},
        ),
    ]
