# Generated by Django 5.2.7 on 2025-10-13 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_manualpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Gateway name (e.g., 'Till 1 - Supplements')", max_length=100, unique=True)),
                ('gateway_type', models.CharField(choices=[('MPESA_TILL', 'M-PESA Till Number'), ('MPESA_PAYBILL', 'M-PESA Paybill'), ('PDQ', 'PDQ/Card Payment'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash Payment'), ('OTHER', 'Other')], help_text='Type of payment gateway', max_length=20)),
                ('gateway_number', models.CharField(db_index=True, help_text='Till number, Paybill number, or identifier', max_length=50, unique=True)),
                ('settlement_type', models.CharField(choices=[('NONE', 'No Settlement Required (100% to shop)'), ('PARENT_TAKES_ALL', 'All to Parent Company'), ('COST_MARKUP', 'Parent gets cost, Shop gets markup'), ('PERCENTAGE', 'Percentage split'), ('CUSTOM', 'Custom calculation')], default='NONE', help_text='How to split payments with parent company', max_length=20)),
                ('settlement_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='If percentage split, what % goes to parent (e.g., 70.00 = 70%)', max_digits=5, null=True)),
                ('requires_parent_settlement', models.BooleanField(default=False, help_text='Does this gateway require settlement with parent company?')),
                ('description', models.TextField(blank=True, help_text='Additional notes about this gateway')),
                ('is_active', models.BooleanField(default=True, help_text='Is this gateway currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='default_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='gateway_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='Which payment gateway this device handles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='Payment gateway this transaction came through', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentgateway'),
        ),
    ]
