# Generated by Django 5.2.7 on 2025-12-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_category_to_product_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_line',
            field=models.ForeignKey(blank=True, help_text='Product line (e.g., Immune Boosters, Cardiovascular Health)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='payments.productline'),
        ),
        migrations.AlterField(
            model_name='productline',
            name='parent_line',
            field=models.ForeignKey(blank=True, help_text='Parent product line if this is a sub-line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sublines', to='payments.productline'),
        ),
    ]
