# Generated by Django 5.2.7 on 2025-11-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentgateway_alter_device_default_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('STOCK_TAKE', 'Stock Take'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Manual Adjustment'), ('RETURN', 'Return'), ('PURCHASE', 'Purchase/Replenishment')], help_text='Type of inventory movement', max_length=20)),
                ('quantity_before', models.IntegerField(help_text='Stock quantity before movement')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after movement')),
                ('quantity_change', models.IntegerField(help_text='Change in quantity (can be negative)')),
                ('reference', models.CharField(blank=True, help_text='Reference (transaction ID, note, etc.)', max_length=200)),
                ('performed_by', models.CharField(blank=True, help_text='User who performed this movement', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.CharField(db_index=True, help_text='Product code (e.g., AP004E)', max_length=50, unique=True)),
                ('prod_name', models.CharField(help_text='Product name', max_length=200)),
                ('sku', models.CharField(db_index=True, help_text='SKU/Barcode identifier for scanner', max_length=100, unique=True)),
                ('sku_name', models.CharField(help_text="Package description (e.g., '100 tablets')", max_length=200)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current selling price', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price from parent company', max_digits=10)),
                ('current_pv', models.DecimalField(decimal_places=2, help_text='Current Point Value for commissions', max_digits=10)),
                ('quantity', models.IntegerField(default=0, help_text='Current stock level')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock level before reorder alert')),
                ('is_active', models.BooleanField(default=True, help_text='Is this product available for sale?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['prod_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_prod_code', models.CharField(max_length=50)),
                ('scanned_prod_name', models.CharField(max_length=200)),
                ('scanned_sku', models.CharField(max_length=100)),
                ('scanned_sku_name', models.CharField(max_length=200)),
                ('scanned_price', models.DecimalField(decimal_places=2, help_text='Price from barcode at scan time', max_digits=10)),
                ('scanned_pv', models.DecimalField(decimal_places=2, help_text='Point Value from barcode at scan time', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Quantity scanned')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × scanned_price', max_digits=10)),
                ('line_cost', models.DecimalField(decimal_places=2, help_text='quantity × product.cost_price (for settlement)', max_digits=10)),
                ('line_pv', models.DecimalField(decimal_places=2, help_text='quantity × scanned_pv', max_digits=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, help_text='User who scanned this item', max_length=255)),
            ],
            options={
                'verbose_name': 'Transaction Line Item',
                'verbose_name_plural': 'Transaction Line Items',
                'ordering': ['scanned_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_fulfilled',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of scanned line items (replaces amount_paid)', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_in_issuance',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this transaction currently being fulfilled? (Only one at a time)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of all line items (for settlement calculation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_pv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Point Value of all line items', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_expected',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use transaction.amount instead', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='DEPRECATED: Use amount_fulfilled instead', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fulfilled__lte', models.F('amount'))), name='amount_fulfilled_cannot_exceed_payment', violation_error_message='Amount fulfilled cannot exceed payment amount'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(help_text='Product affected', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='payments.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Parent category if this is a subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='payments.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='payments.productcategory'),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='product',
            field=models.ForeignKey(help_text='Product reference for inventory tracking', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='payments.product'),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='transaction',
            field=models.ForeignKey(help_text='Transaction this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['-created_at'], name='payments_in_created_5e5d61_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', '-created_at'], name='payments_in_product_bc5148_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='payments_in_movemen_c58545_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prod_code'], name='payments_pr_prod_co_061fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='payments_pr_sku_ded69d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='payments_pr_is_acti_794d81_idx'),
        ),
    ]
