# Generated by Django 5.2.7 on 2026-01-02 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_product_product_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='registration_kit_amount_deducted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted for registration kit(s)', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='registration_kit_issued',
            field=models.BooleanField(db_index=True, default=False, help_text='Has registration kit been issued for this transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='registration_kit_quantity',
            field=models.IntegerField(default=0, help_text='Number of registration kits issued'),
        ),
    ]
