# Generated by Django 5.2.7 on 2025-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_inventorymovement_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_time_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Locked at end-of-day to prevent further modifications'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when transaction was locked (manual or automatic)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='locked_by',
            field=models.CharField(blank=True, help_text='User or system process that locked the transaction', max_length=255),
        ),
    ]
