# Generated by Django 5.2.7 on 2026-01-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_update_products_to_use_buying_price'),
    ]

    operations = [
    ]
