# Generated by Django 5.2.7 on 2025-12-02 07:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_transaction_is_time_locked_transaction_locked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_order_id', models.CharField(db_index=True, help_text='Auto-generated combined order ID (e.g., CMB-20251202-001)', max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Sum of all linked transaction amounts', max_digits=10)),
                ('amount_fulfilled', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total value of products issued against this combined order', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Fulfillment'), ('IN_PROGRESS', 'Fulfillment In Progress'), ('FULFILLED', 'Fully Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current fulfillment status', max_length=20)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name (if known)', max_length=255)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone (if known)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this combined order')),
                ('created_by', models.CharField(help_text='User who created this combined order', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When the order was fully fulfilled', null=True)),
                ('fulfilled_by', models.CharField(blank=True, help_text='User who fulfilled this order', max_length=255)),
            ],
            options={
                'verbose_name': 'Combined Order',
                'verbose_name_plural': 'Combined Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='payments_co_created_30ef2e_idx'), models.Index(fields=['status'], name='payments_co_status_cee11b_idx'), models.Index(fields=['combined_order_id'], name='payments_co_combine_fefc76_idx')],
            },
        ),
        migrations.CreateModel(
            name='CombinedOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_prod_code', models.CharField(help_text='Product code at time of scan', max_length=50)),
                ('scanned_prod_name', models.CharField(help_text='Product name at time of scan', max_length=255)),
                ('scanned_sku', models.CharField(help_text='SKU at time of scan', max_length=50)),
                ('scanned_sku_name', models.CharField(blank=True, help_text='SKU name at time of scan', max_length=255)),
                ('scanned_price', models.DecimalField(decimal_places=2, help_text='Price at time of scan', max_digits=10)),
                ('scanned_pv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PV at time of scan', max_digits=10)),
                ('quantity', models.IntegerField(default=1, help_text='Number of items issued')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line (quantity × price)', max_digits=10)),
                ('line_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost for this line (quantity × cost_price)', max_digits=10)),
                ('line_pv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total PV for this line (quantity × pv)', max_digits=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, help_text='User who scanned this item', max_length=255)),
                ('combined_order', models.ForeignKey(help_text='Combined order this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.combinedorder')),
                ('product', models.ForeignKey(help_text='Product issued', on_delete=django.db.models.deletion.PROTECT, to='payments.product')),
            ],
            options={
                'verbose_name': 'Combined Order Line Item',
                'verbose_name_plural': 'Combined Order Line Items',
                'ordering': ['scanned_at'],
                'indexes': [models.Index(fields=['combined_order', 'scanned_at'], name='payments_co_combine_da2752_idx'), models.Index(fields=['product'], name='payments_co_product_8f0bd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CombinedOrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, help_text='Display order (0=first, 1=second, etc.)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, help_text='User who added this transaction to the combined order', max_length=255)),
                ('combined_order', models.ForeignKey(help_text='The combined order', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.combinedorder')),
                ('transaction', models.ForeignKey(help_text='Individual transaction', on_delete=django.db.models.deletion.PROTECT, related_name='combined_orders', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Combined Order Transaction',
                'verbose_name_plural': 'Combined Order Transactions',
                'ordering': ['sequence', 'added_at'],
                'indexes': [models.Index(fields=['combined_order', 'sequence'], name='payments_co_combine_0be58b_idx'), models.Index(fields=['transaction'], name='payments_co_transac_4f5aa4_idx')],
                'unique_together': {('combined_order', 'transaction')},
            },
        ),
    ]
