# Generated by Django 5.2.7 on 2026-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_cleanup_product_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost price (same as buying price, kept for backward compatibility)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Buying price (what resellers pay us)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_pv',
            field=models.DecimalField(decimal_places=2, help_text='Point Value (PV) for commissions', max_digits=10),
        ),
    ]
