# Generated by Django 5.2.7 on 2025-12-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_combinedorder_combinedorderlineitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSING', 'Processing'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('COMBINED_FULFILLED', 'Combined Order Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_PROCESSED', max_length=20),
        ),
        migrations.CreateModel(
            name='StockTakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Session identifier (STK-YYYYMMDD-HHMMSS)', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Session status', max_length=20)),
                ('created_by', models.CharField(help_text='User who created this session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When session was completed', null=True)),
                ('completed_by', models.CharField(blank=True, help_text='User who completed this session', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Session notes')),
            ],
            options={
                'verbose_name': 'Stock Take Session',
                'verbose_name_plural': 'Stock Take Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='payments_st_created_edaa07_idx'), models.Index(fields=['status'], name='payments_st_status_a8113e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.IntegerField(help_text='Stock quantity before this scan')),
                ('quantity_scanned', models.IntegerField(help_text='Quantity scanned (added to stock)')),
                ('quantity_after', models.IntegerField(help_text='Stock quantity after this scan')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, help_text='When this item was scanned')),
                ('scanned_by', models.CharField(help_text='User who scanned this item', max_length=255)),
                ('product', models.ForeignKey(help_text='Product being counted', on_delete=django.db.models.deletion.PROTECT, to='payments.product')),
                ('session', models.ForeignKey(help_text='Parent stock take session', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.stocktakesession')),
            ],
            options={
                'verbose_name': 'Stock Take Item',
                'verbose_name_plural': 'Stock Take Items',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['session', '-scanned_at'], name='payments_st_session_14e1b4_idx'), models.Index(fields=['product'], name='payments_st_product_c4146f_idx')],
            },
        ),
    ]
