# Generated by Django 5.2.7 on 2025-12-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_transaction_status_stocktakesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='parent_transaction',
            field=models.OneToOneField(blank=True, help_text='Transaction record representing this combined order in the transaction list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combined_order_parent', to='payments.transaction'),
        ),
    ]
