# Generated by Django 5.2.7 on 2025-12-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_combinedorder_parent_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Fulfillment'), ('IN_PROGRESS', 'Fulfillment In Progress'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fully Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current fulfillment status', max_length=20),
        ),
    ]
