# Generated by Claude Code on 2026-01-06

from django.db import migrations
from decimal import Decimal
import os
import sys


def update_inventory_from_excel(apps, schema_editor):
    """
    Update product inventory values from products.xlsx file.

    This migration reads the products.xlsx file and updates:
    - quantity (stock level)
    - current_pv (PV value)
    - current_price (selling price in KSH)
    - cost_price (buying price in KSH)

    Products are matched by SKU/prod_code first, then barcode.
    """
    # Skip file-driven data migration during tests.
    if 'test' in sys.argv or os.environ.get('PYTEST_CURRENT_TEST'):
        print("Skipping Excel inventory update during tests.")
        return

    Product = apps.get_model('payments', 'Product')
    ProductLine = apps.get_model('payments', 'ProductLine')

    try:
        from openpyxl import load_workbook
    except ImportError:
        print("WARNING: openpyxl not installed. Skipping inventory update.")
        return

    # Get the path to the Excel file (should be in backend directory)
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    excel_path = os.path.join(base_dir, 'products.xlsx')

    if not os.path.exists(excel_path):
        print(f"WARNING: Excel file not found at {excel_path}. Skipping inventory update.")
        return

    # Load the Excel file
    wb = load_workbook(excel_path)
    ws = wb.active

    # Get all rows (skip header row)
    rows = list(ws.rows)[1:]

    updated_count = 0
    not_found_count = 0
    current_product_line = None

    print(f"\nUpdating inventory from {excel_path}...")
    print(f"Total rows to process: {len(rows)}\n")

    for idx, row in enumerate(rows, 1):
        # Parse row values
        product_line_name = row[0].value  # Column A: Product Line
        product_name = row[1].value       # Column B: Product Name
        stock = row[2].value              # Column C: Stock
        pv = row[3].value                 # Column D: PV
        selling_price = row[4].value      # Column E: Selling (KSH)
        buying_price = row[5].value       # Column F: Buying (KSH)
        sku = row[6].value                # Column G: SKU
        barcode = row[7].value            # Column H: Barcode (Scan Here)
        # notes = row[8].value            # Column I: Notes

        # Track current product line (product line is only in first row of group)
        if product_line_name:
            current_product_line = product_line_name

        # Validate required fields
        sku_str = str(sku).strip() if sku is not None else ''
        barcode_str = str(barcode).strip() if barcode is not None else ''

        if not sku_str and (not barcode_str or barcode_str == 'print white'):
            print(f"Row {idx}: Skipping product '{product_name}' - no valid SKU/barcode")
            continue

        if stock is None or pv is None or selling_price is None or buying_price is None:
            print(f"Row {idx}: Skipping product '{product_name}' - missing price/stock data")
            continue

        # Find product by SKU/prod_code first, then barcode
        try:
            product = None
            matched_by = None

            if sku_str:
                product = Product.objects.filter(sku=sku_str).first()
                if product:
                    matched_by = f"sku '{sku_str}'"
                else:
                    product = Product.objects.filter(prod_code=sku_str).first()
                    if product:
                        matched_by = f"prod_code '{sku_str}'"

            if not product and barcode_str and barcode_str != 'print white':
                product = Product.objects.filter(barcode=barcode_str).first()
                if product:
                    matched_by = f"barcode '{barcode_str}'"

            if not product:
                raise Product.DoesNotExist

            # Update inventory values
            old_quantity = product.quantity
            old_pv = product.current_pv
            old_selling = product.current_price
            old_buying = product.cost_price

            product.quantity = int(stock)
            product.current_pv = Decimal(str(pv))
            product.current_price = Decimal(str(selling_price))
            product.cost_price = Decimal(str(buying_price))

            # Update product name if it's different
            if product.prod_name != product_name:
                old_name = product.prod_name
                product.prod_name = product_name
                print(f"Row {idx}: Updated name from '{old_name}' to '{product_name}'")

            # Update product line if it exists and is different
            if current_product_line:
                try:
                    product_line = ProductLine.objects.get(name=current_product_line)
                    if product.product_line != product_line:
                        product.product_line = product_line
                        print(f"Row {idx}: Updated product line to '{current_product_line}' for '{product_name}'")
                except ProductLine.DoesNotExist:
                    pass  # Keep existing product line

            product.save()

            print(f"Row {idx}: Updated '{product_name}' (matched by {matched_by})")
            print(f"  Stock: {old_quantity} → {stock}")
            print(f"  PV: {old_pv} → {pv}")
            print(f"  Selling: {old_selling} → {selling_price}")
            print(f"  Buying: {old_buying} → {buying_price}")

            updated_count += 1

        except Product.DoesNotExist:
            if sku_str:
                print(f"Row {idx}: Product not found with SKU '{sku_str}' ('{product_name}')")
            elif barcode_str:
                print(f"Row {idx}: Product not found with barcode '{barcode_str}' ('{product_name}')")
            else:
                print(f"Row {idx}: Product not found ('{product_name}')")
            not_found_count += 1

    print(f"\n{'='*60}")
    print(f"Inventory update completed!")
    print(f"Updated: {updated_count} products")
    print(f"Not found: {not_found_count} products")
    print(f"{'='*60}\n")


def reverse_inventory_update(apps, schema_editor):
    """
    Reverse operation is not implemented as we don't have the original values.
    This is a data migration, so reversal is not straightforward.
    """
    print("WARNING: Reverse operation not implemented for inventory update.")
    print("Original inventory values were not saved.")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_sync_sku_with_prod_code'),
    ]

    operations = [
        migrations.RunPython(update_inventory_from_excel, reverse_inventory_update),
    ]
