# Generated by Django 5.2.7 on 2025-12-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_add_partially_fulfilled_to_combined_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='is_time_locked',
            field=models.BooleanField(default=False, help_text='True if locked at end-of-day (prevents further modifications)'),
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When this order was time-locked', null=True),
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='locked_by',
            field=models.CharField(blank=True, help_text='Reason or user who locked this order', max_length=255),
        ),
    ]
