# Generated by Django 5.2.7 on 2026-01-12 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_update_inventory_from_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_code',
            field=models.CharField(db_index=True, help_text='Product Code/SKU (same value, e.g., AP004E)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='SKU (same as prod_code, kept for backward compatibility)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_name',
            field=models.CharField(help_text="Package description (e.g., '100 tablets', '60 capsules')", max_length=200),
        ),
        migrations.CreateModel(
            name='DailyStockReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reconciliation_date', models.DateField(db_index=True, help_text='Date of reconciliation (typically end of day)', unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', help_text='DRAFT = editable, CONFIRMED = applied to inventory', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Overall notes for the day's reconciliation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when reconciliation was confirmed and applied', null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='User who confirmed and applied this reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Stock Reconciliation',
                'verbose_name_plural': 'Daily Stock Reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_stock', models.IntegerField(help_text='Stock quantity at start of reconciliation')),
                ('quantity_added', models.IntegerField(default=0, help_text='Quantity added (e.g., new shipment received)')),
                ('quantity_deducted', models.IntegerField(default=0, help_text='Quantity deducted (e.g., damaged, stolen, shrinkage)')),
                ('closing_stock', models.IntegerField(help_text='Calculated closing stock (opening + added - deducted)')),
                ('notes', models.TextField(blank=True, help_text='Notes about this specific adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product being adjusted', on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='payments.product')),
                ('reconciliation', models.ForeignKey(help_text='Parent reconciliation record', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payments.dailystockreconciliation')),
            ],
            options={
                'verbose_name': 'Stock Adjustment Item',
                'verbose_name_plural': 'Stock Adjustment Items',
                'ordering': ['product__prod_name'],
            },
        ),
        migrations.AddIndex(
            model_name='dailystockreconciliation',
            index=models.Index(fields=['-reconciliation_date'], name='payments_da_reconci_8254f0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockreconciliation',
            index=models.Index(fields=['status'], name='payments_da_status_b320d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockreconciliation',
            index=models.Index(fields=['created_at'], name='payments_da_created_af5574_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentitem',
            index=models.Index(fields=['reconciliation', 'product'], name='payments_st_reconci_8b336d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentitem',
            index=models.Index(fields=['product'], name='payments_st_product_dd2aea_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentitem',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'product'), name='unique_reconciliation_product'),
        ),
    ]
