# Generated by Django 5.2.7 on 2026-01-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_product_prod_code_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='quantity_replenished',
            field=models.IntegerField(default=0, help_text='Quantity replenished from stock take sessions (auto-calculated, read-only)'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentitem',
            name='closing_stock',
            field=models.IntegerField(help_text='Actual closing stock counted during stock take'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentitem',
            name='quantity_added',
            field=models.IntegerField(default=0, help_text='Quantity added (manual adjustments, corrections)'),
        ),
    ]
