# Generated by Django 5.2.7 on 2025-12-09 12:27

from django.db import migrations


def assign_default_gateway_to_devices(apps, schema_editor):
    """
    Assign M-Pesa Main Till gateway to all devices that have NULL gateway.
    This migration is required before making gateway field non-nullable.
    """
    Device = apps.get_model('payments', 'Device')
    PaymentGateway = apps.get_model('payments', 'PaymentGateway')

    # Get M-Pesa Main Till gateway (id=1)
    try:
        default_gateway = PaymentGateway.objects.get(id=1)
    except PaymentGateway.DoesNotExist:
        # If M-Pesa Main Till doesn't exist, get the first active gateway
        default_gateway = PaymentGateway.objects.filter(is_active=True).first()

        if not default_gateway:
            # If no active gateways exist, skip this migration
            print("WARNING: No active payment gateways found. Skipping device gateway assignment.")
            return

    # Assign default gateway to all devices with NULL gateway
    devices_updated = Device.objects.filter(gateway__isnull=True).update(gateway=default_gateway)

    if devices_updated > 0:
        print(f"Assigned {default_gateway.name} to {devices_updated} device(s) with NULL gateway")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - does nothing since we don't want to clear gateways
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_combinedorder_is_time_locked_combinedorder_locked_at_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_gateway_to_devices, reverse_migration),
    ]
