# Generated by Django 5.2.7 on 2025-12-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_assign_default_gateway_to_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(
                help_text='Which payment gateway this device handles (required)',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='devices',
                to='payments.paymentgateway'
            ),
        ),
    ]
