# Generated by Django 5.2.7 on 2026-01-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_add_quantity_replenished_to_stockadjustmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='opening_stock_baseline',
            field=models.IntegerField(blank=True, help_text='Manual baseline override for opening stock (used for initial setup, ignores previous reconciliation)', null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustmentitem',
            name='opening_stock',
            field=models.IntegerField(help_text="Stock quantity at start of day (from previous day's closing or baseline)"),
        ),
    ]
