# Generated by Django 5.2.7 on 2026-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_add_opening_stock_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_fulfilled_before_activation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount fulfilled before this issuance session started (for cancel restore)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_before_activation',
            field=models.CharField(blank=True, choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSING', 'Processing'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('COMBINED_FULFILLED', 'Combined Order Fulfilled'), ('CANCELLED', 'Cancelled')], help_text='Status before this issuance session started (for cancel restore)', max_length=20, null=True),
        ),
    ]
