# Generated by Django 5.2.7 on 2026-01-15 08:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_add_issuance_state_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedorder',
            name='amount_fulfilled_before_activation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount fulfilled before this issuance session started (for cancel restore)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='base_amount_fulfilled',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of amount_fulfilled from child transactions (preserved from before combining)', max_digits=10),
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='status_before_activation',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Fulfillment'), ('IN_PROGRESS', 'Fulfillment In Progress'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fully Fulfilled'), ('CANCELLED', 'Cancelled')], help_text='Status before this issuance session started (for cancel restore)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='combinedorderlineitem',
            name='copied_from_transaction',
            field=models.ForeignKey(blank=True, help_text='If this item was copied from a partially fulfilled transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to_combined_items', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='combinedorderlineitem',
            name='is_inventory_deducted',
            field=models.BooleanField(default=False, help_text='True if inventory has been deducted for this item (on completion)'),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='is_inventory_deducted',
            field=models.BooleanField(default=False, help_text='True if inventory has been deducted for this item (on issuance completion)'),
        ),
    ]
