# Generated by Django 5.2.7 on 2026-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_fix_existing_line_items_deducted_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='is_parent_company',
            field=models.BooleanField(default=False, help_text='Is this the parent company gateway (for reconciliation calculations)?'),
        ),
    ]
