# Generated by Django 5.2.7 on 2026-02-26 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_generatedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Promotion name (e.g., 'Elements Bundle Discount')", max_length=200)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount (KES)'), ('PERCENTAGE', 'Percentage (%)')], default='FIXED', help_text='Whether the discount is a fixed KES amount or a percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Fixed KES amount or percentage value (e.g., 1620.00 or 10.00)', max_digits=10)),
                ('start_date', models.DateTimeField(help_text='When the promotion becomes active')),
                ('end_date', models.DateTimeField(help_text='When the promotion expires')),
                ('is_active', models.BooleanField(default=True, help_text='Manual toggle to enable/disable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity of this product required to qualify')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='payments.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='payments.promotion')),
            ],
            options={
                'verbose_name': 'Promotion Product',
                'verbose_name_plural': 'Promotion Products',
                'unique_together': {('promotion', 'product')},
            },
        ),
    ]
