# Generated by Django 5.2.7 on 2026-02-27 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_stocktakesession_kit_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Location name (e.g., 'Main Shop', 'Nairobi Expo')", max_length=100, unique=True)),
                ('location_type', models.CharField(choices=[('MAIN', 'Main Shop'), ('FIELD', 'Field Location')], db_index=True, default='FIELD', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='combinedorder',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where this combined order is being fulfilled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_orders', to='payments.location'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where this transaction is being fulfilled (set at activation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text="User's current working location (defaults to Main Shop)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='payments.location'),
        ),
    ]
