# Generated by Django 5.2.7 on 2026-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_merch_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessage',
            name='is_relayed',
            field=models.BooleanField(db_index=True, default=False, help_text='Was this message relayed from another branch instance?'),
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='source_branch',
            field=models.CharField(blank=True, help_text='Name of the branch that originally received this SMS (empty = local)', max_length=100),
        ),
    ]
