# Generated by Django 5.2.7 on 2026-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_rawmessage_is_relayed_rawmessage_source_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Rich product description for the website catalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public URL to product image for the website', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchandisecatalogitem',
            name='item_type',
            field=models.CharField(choices=[('COFFEE', 'Coffee'), ('SET', 'Shirt + Hat Set')], db_index=True, max_length=20),
        ),
    ]
